name: forwarding-discord-telegram
services:
  bot:
    image: tapnisu/forwarding-discord-telegram:main
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_TOPIC_ID: ${TELEGRAM_TOPIC_ID}
    volumes:
      - ./config.json:/app/config.json
    restart: unless-stopped
